In [12]:
import interpolator.util as util
import pandas as pd
import numpy as np
import os

folder_path = os.path.dirname('C:/Users/mikel/Desktop/5000_runs/')
params_path = os.path.join(folder_path, 'parameters.log')
grid_path = os.path.join(folder_path, 'grid.csv')

param_names = ['index', 'log_lsun', 't_exp', 'v_start', 'X', 'Z']
X, y, wav_mod = util.read_grid_runs(params_path, folder_path, param_names)
grid = pd.read_csv(grid_path)

In [18]:
# Create new grid with failed entries
ran_i = X['index'].to_numpy(int)
grid_i = grid['index'].to_numpy(int)
failed_i = np.array([x for x in grid_i if x not in ran_i])
print(np.sort(ran_i))
print(grid_i)
print(failed_i)

mask = np.array([x in failed_i for x in grid['index']])
new_grid = grid[mask]
new_grid.to_csv('grid.csv', index=False)

[   0    1    2 ... 4997 4998 4999]
[   0    1    2 ... 4997 4998 4999]
[  50   51   55 ... 4969 4970 4975]
